In [1]:
#Contoh Dokumen
d1 = "Pandemi korona indonesia belum berakhir psbb blt kartu prakerja" #Topik 0: pandemi
d2 = "ekonomi reses dolar naik phk inflasi pertumbuhan ekonomi" #Topik 1: ekonomi
d3 = "ekonomi uang moneter pasar uang jual beli turun tutup reses" #Topik 1: ekonomi
d4 = "inflasi uang pasar saham jual untung ekonomi turun inflasi" #Topik 1: ekonomi
#d5 = "teknologi gadget internet smartphone android informasi"
#Gabungkan dokumen menjadi satu list -> Corpus
Docs = [d1, d2, d3, d4]
#Ekstraksi fitur / representasi dokumen menggunakan TF
from sklearn.feature_extraction.text import CountVectorizer
tf_vectorizer = CountVectorizer(max_df=1.0, min_df=1)
tf = tf_vectorizer.fit_transform(Docs)
#hasil representasi
tf_terms = tf_vectorizer.get_feature_names()
print(tf_vectorizer.get_feature_names())
matrix = tf.toarray()
print(matrix)

['beli', 'belum', 'berakhir', 'blt', 'dolar', 'ekonomi', 'indonesia', 'inflasi', 'jual', 'kartu', 'korona', 'moneter', 'naik', 'pandemi', 'pasar', 'pertumbuhan', 'phk', 'prakerja', 'psbb', 'reses', 'saham', 'turun', 'tutup', 'uang', 'untung']
[[0 1 1 1 0 0 1 0 0 1 1 0 0 1 0 0 0 1 1 0 0 0 0 0 0]
 [0 0 0 0 1 2 0 1 0 0 0 0 1 0 0 1 1 0 0 1 0 0 0 0 0]
 [1 0 0 0 0 1 0 0 1 0 0 1 0 0 1 0 0 0 0 1 0 1 1 2 0]
 [0 0 0 0 0 1 0 2 1 0 0 0 0 0 1 0 0 0 0 0 1 1 0 1 1]]


In [2]:
# panggil class LDA
from sklearn.decomposition import LatentDirichletAllocation as LDA
n_topics = 3 #untuk mendapatkan jumlah topik terbaik perlu trial
lda = LDA(n_components=n_topics, learning_method='batch', random_state=0).fit(tf)
lda

LatentDirichletAllocation(n_components=3, random_state=0)

In [3]:
#training LDA
vsm_topics = lda.transform(tf)
#tampilkan hasil
print(vsm_topics.shape)
vsm_topics

(4, 3)


array([[0.93231556, 0.03412529, 0.03355915],
       [0.03924175, 0.03769985, 0.9230584 ],
       [0.03251976, 0.03084973, 0.93663051],
       [0.9210004 , 0.03403642, 0.04496318]])

In [4]:
#Tampilkan nilai-nilai setiap fitur
print(lda.components_)


[[0.33361493 1.33220356 1.33220356 1.33220356 0.33367267 1.29806683
  1.33220356 2.33534335 1.32575752 1.33220356 1.33220356 0.33361493
  0.33367267 1.33220356 1.32575752 0.33367267 0.33367267 1.33220356
  1.33220356 0.33362656 1.33183967 1.32575752 0.33361493 1.31157175
  1.33183967]
 [0.33411362 0.3342122  0.3342122  0.3342122  0.33431432 0.33506001
  0.3342122  0.33514705 0.33499564 0.3342122  0.3342122  0.33411362
  0.33431432 0.3342122  0.33499564 0.33431432 0.33431432 0.3342122
  0.3342122  0.33416472 0.33421601 0.33499564 0.33411362 0.33495281
  0.33421601]
 [1.33227145 0.33358425 0.33358425 0.33358425 1.33201301 3.36687316
  0.33358425 1.3295096  1.33924685 0.33358425 0.33358425 1.33227145
  1.33201301 0.33358425 1.33924685 1.33201301 1.33201301 0.33358425
  0.33358425 2.33220872 0.33394432 1.33924685 1.33227145 2.35347544
  0.33394432]]


In [5]:
#hasil label topic model untuk setiap dokumen
import numpy as np
topics = np.argmax(vsm_topics, axis=1)
topics

array([0, 2, 2, 0], dtype=int64)

In [6]:
#mencetak word fitur dengan nilai tertinggi pada setiap topik
n_top_words = 4 # jumlah fitur tertinggi yang kita tentukan
topic_words = {}
for topic, comp in enumerate(lda.components_):
 word_idx = np.argsort(comp)[::-1][:n_top_words]
 # store the words most relevant to the topic
 topic_words[topic] = [tf_vectorizer.get_feature_names()[i]+' '+str(comp[i]) for i in word_idx]

In [7]:
for topic, words in topic_words.items():
 print('Topic: %d' % topic)
 print(' %s' % ', '.join(words))

Topic: 0
 inflasi 2.335343346391772, pandemi 1.3322035561949337, belum 1.3322035561949337, kartu 1.3322035561949337
Topic: 1
 inflasi 0.33514704880953633, ekonomi 0.3350600077761751, pasar 0.3349956360714814, turun 0.3349956360714814
Topic: 2
 ekonomi 3.366873157277532, uang 2.3534754366602657, reses 2.3322087189684098, turun 1.3392468468277479
