In [1]:
import pandas as pd
import re
import matplotlib.pyplot as plt
%matplotlib inline

<h1>
Ambil data dari CSV
</h1>

In [2]:
import pandas as pd
data = pd.read_csv("javaheritagehotel.csv",delimiter=";") # read file csv nya dulu yang java heritage
data

customer_name                  customer_judul_komen  \
0               andy S                     Hotel yang nyaman   
1      Fabian Hernanda                     Keluarga Hernawan   
2        christiandi a  Kamarnya nyaman,kolam renangnya aman   
3           Fajar Heks                           Hotel juara   
4          Yono Suyono                     nyaman dan tenang   
..                 ...                                   ...   
114          Irwan_Joe               Dari dinasti ke horison   
115           Rachel U       Semoga dapat menjadi lebih baik   
116      Anu_Singapore                     Di atas rata-rata   
117       agus budiman                       harga rata-rata   
118  pleasantinterlude        Baik tetapi dapat ditingkatkan   

                              customer_judul_komen_url  \
0    https://www.tripadvisor.co.id/ShowUserReviews-...   
1    https://www.tripadvisor.co.id/ShowUserReviews-...   
2    https://www.tripadvisor.co.id/ShowUserReviews-...   
3    https://www.tripadvisor.co.id/ShowUserReviews-...   
4    https://www.tripadvisor.co.id/ShowUserReviews-...   
..                                                 ...   
114  https://www.tripadvisor.co.id/ShowUserReviews-...   
115  https://www.tripadvisor.co.id/ShowUserReviews-...   
116  https://www.tripadvisor.co.id/ShowUserReviews-...   
117  https://www.tripadvisor.co.id/ShowUserReviews-...   
118  https://www.tripadvisor.co.id/ShowUserReviews-...   

                                    customer_isi_komen  
0    Salah satu hotel yang terbaik di Purwokerto, b...  
1    Mobil Delica Hotel Java Heritage Keluarga Enda...  
2    Hotel ini layak jadi pilihan pertama bila anda...  
3    Hotel juara di purwokerto.... lokasi di tengah...  
4    kemegahan bangunan dan fasilitas penunjang kad...  
..                                                 ...  
114  Ini adalah pertama kalinya saya tinggal di hor...  
115  Pertama saya pilih di bangunan tua yang indah....  
116  Kamar yang luas - hotel yang nyaman. Layanan l...  
117  salah satu hotel terbaik di purwokerto dengan ...  
118  Tinggal di hotel untuk malam. Kesan pertama ad...  

[119 rows x 4 columns]

In [3]:
pip install Sastrawi

Note: you may need to restart the kernel to use updated packages.


<h1>
Pembersihan Data
</h1>

In [4]:
import Sastrawi
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

slangs={"@": "di", "abis": "habis", "ad": "ada", "adlh": "adalah", "afaik": "as far as i know",
        "ahaha": "haha", "aj": "saja", "ajep-ajep": "dunia gemerlap", "ak": "saya", "akika": "aku",
        "akkoh": "aku", "akuwh": "aku", "alay": "norak", "alow": "halo", "ambilin": "ambilkan",
        "ancur": "hancur", "anjrit": "anjing", "anter": "antar", "ap2": "apa-apa", "apasih": "apa sih",
        "apes": "sial", "aps": "apa", "aq": "saya", "aquwh": "aku", "asbun": "asal bunyi", "aseekk": "asyik",
        "asekk": "asyik", "asem": "asam", "aspal": "asli tetapi palsu", "astul": "asal tulis", "ato": "atau",
        "au ah": "tidak mau tahu", "awak": "saya", "ay": "sayang", "ayank": "sayang", "b4": "sebelum",
        "bakalan": "akan", "bandes": "bantuan desa", "bangedh": "banget", "banpol": "bantuan polisi",
        "banpur": "bantuan tempur", "basbang": "basi", "bcanda": "bercanda", "bdg": "bandung",
        "begajulan": "nakal", "beliin": "belikan", "bencong": "banci", "bentar": "sebentar", "ber3": "bertiga",
        "beresin": "membereskan", "bete": "bosan", "beud": "banget", "bg": "abang", "bgmn": "bagaimana",
        "bgt": "banget", "bijimane": "bagaimana", "bintal": "bimbingan mental", "bkl": "akan",
        "bknnya": "bukannya", "blegug": "bodoh", "blh": "boleh", "bln": "bulan", "blum": "belum", "bnci": "benci",
        "bnran": "yang benar", "bodor": "lucu", "bokap": "ayah", "boker": "buang air besar", "bokis": "bohong",
        "boljug": "boleh juga", "bonek": "bocah nekat", "boyeh": "boleh", "br": "baru", "brg": "bareng",
        "bro": "saudara laki-laki", "bru": "baru", "bs": "bisa", "bsen": "bosan", "bt": "buat", "btw": "ngomong-ngomong",
        "buaya": "tidak setia", "bubbu": "tidur", "bubu": "tidur", "bumil": "ibu hamil", "bw": "bawa",
        "bwt": "buat", "byk": "banyak", "byrin": "bayarkan", "cabal": "sabar", "cadas": "keren",
        "calo": "makelar", "can": "belum", "capcus": "pergi", "caper": "cari perhatian", "ce": "cewek",
        "cekal": "cegah tangkal", "cemen": "penakut", "cengengesan": "tertawa", "cepet": "cepat",
        "cew": "cewek", "chuyunk": "sayang", "cimeng": "ganja", "cipika cipiki": "cium pipi kanan cium pipi kiri",
        "ciyh": "sih", "ckepp": "cakep", "ckp": "cakep", "cmiiw": "correct me if i'm wrong", "cmpur": "campur",
        "cong": "banci", "conlok": "cinta lokasi", "cowwyy": "maaf", "cp": "siapa", "cpe": "capek", "cppe": "capek",
        "cucok": "cocok", "cuex": "cuek", "cumi": "Cuma miscall", "cups": "culun",
        "curanmor": "pencurian kendaraan bermotor", "curcol": "curahan hati colongan",
        "cwek": "cewek", "cyin": "cinta", "d": "di", "dah": "deh", "dapet": "dapat", "de": "adik",
        "dek": "adik", "demen": "suka", "deyh": "deh", "dgn": "dengan", "diancurin": "dihancurkan",
        "dimaafin": "dimaafkan", "dimintak": "diminta", "disono": "di sana", "dket": "dekat",
        "dkk": "dan kawan-kawan", "dll": "dan lain-lain", "dlu": "dulu", "dngn": "dengan", "dodol": "bodoh",
        "doku": "uang", "dongs": "dong", "dpt": "dapat", "dri": "dari", "drmn": "darimana", "drtd": "dari tadi",
        "dst": "dan seterusnya", "dtg": "datang", "duh": "aduh", "duren": "durian", "ed": "edisi",
        "egp": "emang gue pikirin", "eke": "aku", "elu": "kamu", "emangnya": "memangnya", "emng": "memang",
        "endak": "tidak", "enggak": "tidak", "envy": "iri", "ex": "mantan", "fax": "facsimile",
        "fifo": "first in first out", "folbek": "follow back", "fyi": "sebagai informasi", "gaada": "tidak ada uang",
        "gag": "tidak", "gaje": "tidak jelas", "gak papa": "tidak apa-apa", "gan": "juragan", "gaptek": "gagap teknologi",
        "gatek": "gagap teknologi", "gawe": "kerja", "gbs": "tidak bisa", "gebetan": "orang yang disuka",
        "geje": "tidak jelas", "gepeng": "gelandangan dan pengemis", "ghiy": "lagi", "gile": "gila",
        "gimana": "bagaimana", "gino": "gigi nongol", "githu": "gitu", "gj": "tidak jelas", "gmana": "bagaimana",
        "gn": "begini", "goblok": "bodoh", "golput": "golongan putih", "gowes": "mengayuh sepeda",
        "gpny": "tidak punya", "gr": "gede rasa", "gretongan": "gratisan", "gtau": "tidak tahu",
        "gua": "saya", "guoblok": "goblok", "gw": "saya", "ha": "tertawa", "haha": "tertawa",
        "hallow": "halo", "hankam": "pertahanan dan keamanan", "hehe": "he", "helo": "halo", "hey": "hai",
        "hlm": "halaman", "hny": "hanya", "hoax": "isu bohong", "hr": "hari", "hrus": "harus",
        "hubdar": "perhubungan darat", "huff": "mengeluh", "hum": "rumah", "humz": "rumah",
        "ilang": "hilang", "ilfil": "tidak suka", "imho": "in my humble opinion", "imoetz": "imut",
        "item": "hitam", "itungan": "hitungan", "iye": "iya", "ja": "saja", "jadiin": "jadi",
        "jaim": "jaga image", "jayus": "tidak lucu", "jdi": "jadi", "jem": "jam", "jga": "juga",
        "jgnkan": "jangankan", "jir": "anjing", "jln": "jalan", "jomblo": "tidak punya pacar",
        "jubir": "juru bicara", "jutek": "galak", "k": "ke", "kab": "kabupaten", "kabor": "kabur",
        "kacrut": "kacau", "kadiv": "kepala divisi", "kagak": "tidak", "kalo": "kalau", "kampret": "sialan",
        "kamtibmas": "keamanan dan ketertiban masyarakat", "kamuwh": "kamu", "kanwil": "kantor wilayah",
        "karna": "karena", "kasubbag": "kepala subbagian", "katrok": "kampungan", "kayanya": "kayaknya",
        "kbr": "kabar", "kdu": "harus", "kec": "kecamatan", "kejurnas": "kejuaraan nasional",
        "kekeuh": "keras kepala", "kel": "kelurahan", "kemaren": "kemarin", "kepengen": "mau", "kepingin": "mau",
        "kepsek": "kepala sekolah", "kesbang": "kesatuan bangsa", "kesra": "kesejahteraan rakyat",
        "ketrima": "diterima", "kgiatan": "kegiatan", "kibul": "bohong", "kimpoi": "kawin", "kl": "kalau",
        "klianz": "kalian", "kloter": "kelompok terbang", "klw": "kalau", "km": "kamu", "kmps": "kampus",
        "kmrn": "kemarin", "knal": "kenal", "knp": "kenapa", "kodya": "kota madya",
        "komdis": "komisi disiplin", "komsov": "komunis sovyet", "kongkow": "kumpul bareng teman-teman",
        "kopdar": "kopi darat", "korup": "korupsi", "kpn": "kapan", "krenz": "keren", "krm": "kirim","kt": "kita", "ktmu": "ketemu", "ktr": "kantor", "kuper": "kurang pergaulan", "kw": "imitasi",
        "kyk": "seperti", "la": "lah", "lam": "salam", "lamp": "lampiran", "lanud": "landasan udara",
        "latgab": "latihan gabungan", "lebay": "berlebihan", "leh": "boleh", "lelet": "lambat",
        "lemot": "lambat", "lgi": "lagi", "lgsg": "langsung", "liat": "lihat", "litbang": "penelitian dan pengembangan",
        "lmyn": "lumayan", "lo": "kamu", "loe": "kamu", "lola": "lambat berfikir", "louph": "cinta", "low": "kalau",
        "lp": "lupa", "luber": "langsung, umum, bebas, dan rahasia", "luchuw": "lucu", "lum": "belum", "luthu": "lucu",
        "lwn": "lawan", "maacih": "terima kasih", "mabal": "bolos", "macem": "macam", "macih": "masih",
        "maem": "makan", "magabut": "makan gaji buta", "maho": "homo", "mak jang": "kaget", "maksain": "memaksa",
        "malem": "malam", "mam": "makan", "maneh": "kamu", "maniez": "manis", "mao": "mau", "masukin": "masukkan",
        "melu": "ikut", "mepet": "dekat sekali", "mgu": "minggu", "migas": "minyak dan gas bumi",
        "mikol": "minuman beralkohol", "miras": "minuman keras", "mlah": "malah", "mngkn": "mungkin",
        "mo": "mau", "mokad": "mati", "moso": "masa", "mpe": "sampai", "msk": "masuk", "mslh": "masalah",
        "mt": "makan teman", "mubes": "musyawarah besar", "mulu": "melulu", "mumpung": "selagi",
        "munas": "musyawarah nasional", "muntaber": "muntah dan berak", "musti": "mesti", "muupz": "maaf",
        "mw": "now watching", "n": "dan", "nanam": "menanam", "nanya": "bertanya", "napa": "kenapa",
        "napi": "narapidana", "napza": "narkotika, alkohol, psikotropika, dan zat adiktif ",
        "narkoba": "narkotika, psikotropika, dan obat terlarang", "nasgor": "nasi goreng", "nda": "tidak",
        "ndiri": "sendiri", "ne": "ini", "nekolin": "neokolonialisme", "nembak": "menyatakan cinta",
        "ngabuburit": "menunggu berbuka puasa", "ngaku": "mengaku", "ngambil": "mengambil",
        "nganggur": "tidak punya pekerjaan", "ngapah": "kenapa", "ngaret": "terlambat", "ngasih": "memberikan",
        "ngebandel": "berbuat bandel", "ngegosip": "bergosip", "ngeklaim": "mengklaim", "ngeksis": "menjadi eksis",
        "ngeles": "berkilah", "ngelidur": "menggigau", "ngerampok": "merampok", "ngga": "tidak", "ngibul": "berbohong",
        "ngiler": "mau", "ngiri": "iri", "ngisiin": "mengisikan", "ngmng": "bicara", "ngomong": "bicara",
        "ngubek2": "mencari-cari", "ngurus": "mengurus", "nie": "ini", "nih": "ini", "niyh": "nih", "nmr": "nomor",
        "nntn": "nonton", "nobar": "nonton bareng", "np": "now playing", "ntar": "nanti", "ntn": "nonton",
        "numpuk": "bertumpuk", "nutupin": "menutupi", "nyari": "mencari", "nyekar": "menyekar", "nyicil": "mencicil",
        "nyoblos": "mencoblos", "nyokap": "ibu", "ogah": "tidak mau", "ol": "online", "ongkir": "ongkos kirim",
        "oot": "out of topic", "org2": "orang-orang", "ortu": "orang tua", "otda": "otonomi daerah",
        "otw": "on the way, sedang di jalan", "pacal": "pacar", "pake": "pakai", "pala": "kepala",
        "pansus": "panitia khusus", "parpol": "partai politik", "pasutri": "pasangan suami istri", "pd": "pada",
        "pede": "percaya diri", "pelatnas": "pemusatan latihan nasional", "pemda": "pemerintah daerah",
        "pemkot": "pemerintah kota", "pemred": "pemimpin redaksi", "penjas": "pendidikan jasmani",
        "perda": "peraturan daerah", "perhatiin": "perhatikan", "pesenan": "pesanan", "pgang": "pegang", "pi": "tapi",
        "pilkada": "pemilihan kepala daerah", "pisan": "sangat", "pk": "penjahat kelamin", "plg": "paling",
        "pmrnth": "pemerintah", "polantas": "polisi lalu lintas", "ponpes": "pondok pesantren", "pp": "pulang pergi",
        "prg": "pergi", "prnh": "pernah", "psen": "pesan", "pst": "pasti", "pswt": "pesawat", "pw": "posisi nyaman",
        "qmu": "kamu", "rakor": "rapat koordinasi", "ranmor": "kendaraan bermotor", "re": "reply", "ref": "referensi",
        "rehab": "rehabilitasi", "rempong": "sulit", "repp": "balas", "restik": "reserse narkotika", "rhs": "rahasia",
        "rmh": "rumah", "ru": "baru", "ruko": "rumah toko", "rusunawa": "rumah susun sewa", "ruz": "terus",
        "saia": "saya", "salting": "salah tingkah", "sampe": "sampai", "samsek": "sama sekali", "sapose": "siapa",
        "satpam": "satuan pengamanan", "sbb": "sebagai berikut", "sbh": "sebuah", "sbnrny": "sebenarnya",
        "scr": "secara", "sdgkn": "sedangkan", "sdkt": "sedikit", "se7": "setuju", "sebelas dua belas": "mirip",
        "sembako": "sembilan bahan pokok", "sempet": "sempat", "sendratari": "seni drama tari", "sgt": "sangat",
        "shg": "sehingga", "siech": "sih", "sikon": "situasi dan kondisi", "sinetron": "sinema elektronik",
        "siramin": "siramkan", "sj": "saja", "skalian": "sekalian", "sklh": "sekolah", "skt": "sakit",
        "slesai": "selesai", "sll": "selalu", "slma": "selama", "slsai": "selesai", "smpt": "sempat", "smw": "semua",
        "sndiri": "sendiri", "soljum": "sholat jumat", "songong": "sombong", "sory": "maaf", "sosek": "sosial-ekonomi",
        "sotoy": "sok tahu", "spa": "siapa", "sppa": "siapa", "spt": "seperti", "srtfkt": "sertifikat",
        "stiap": "setiap", "stlh": "setelah", "suk": "masuk", "sumpek": "sempit", "syg": "sayang", "t4": "tempat",
        "tajir": "kaya", "tau": "tahu", "taw": "tahu", "td": "tadi", "tdk": "tidak", "teh": "kakak perempuan",
        "telat": "terlambat", "telmi": "telat berpikir", "temen": "teman", "tengil": "menyebalkan", "tepar": "terkapar",
        "tggu": "tunggu", "tgu": "tunggu", "thankz": "terima kasih", "thn": "tahun", "tilang": "bukti pelanggaran",
        "tipiwan": "TvOne", "tks": "terima kasih", "tlp": "telepon", "tls": "tulis", "tmbah": "tambah",
        "tmen2": "teman-teman", "tmpah": "tumpah", "tmpt": "tempat", "tngu": "tunggu", "tnyta": "ternyata",
        "tokai": "tai", "toserba": "toko serba ada", "tpi": "tapi", "trdhulu": "terdahulu", "trima": "terima kasih",
        "trm": "terima", "trs": "terus", "trutama": "terutama", "ts": "penulis", "tst": "tahu sama tahu",
        "ttg": "tentang", "tuch": "tuh", "tuir": "tua", "tw": "tahu", "u": "kamu", "ud": "sudah", "udah": "sudah",
        "ujg": "ujung", "ul": "ulangan", "unyu": "lucu", "uplot": "unggah", "urang": "saya", "usah": "perlu",
        "utk": "untuk", "valas": "valuta asing", "w/": "dengan", "wadir": "wakil direktur", "wamil": "wajib militer",
        "warkop": "warung kopi", "warteg": "warung tegal", "wat": "buat", "wkt": "waktu", "wtf": "what the fuck",
        "xixixi": "tertawa", "ya": "iya", "yap": "iya", "yaudah": "ya sudah", "yawdah": "ya sudah", "yg": "yang",
        "yl": "yang lain", "yo": "iya", "yowes": "ya sudah", "yup": "iya", "7an": "tujuan", "ababil": "abg labil",
        "acc": "accord", "adlah": "adalah", "adoh": "aduh", "aha": "tertawa", "aing": "saya", "aja": "saja",
        "ajj": "saja", "aka": "dikenal juga sebagai", "akko": "aku", "akku": "aku", "akyu": "aku",
        "aljasa": "asal jadi saja", "ama": "sama", "ambl": "ambil", "anjir": "anjing", "ank": "anak", "ap": "apa",
        "apaan": "apa", "ape": "apa", "aplot": "unggah", "apva": "apa", "aqu": "aku", "asap": "sesegera mungkin",
        "aseek": "asyik", "asek": "asyik", "aseknya": "asyiknya", "asoy": "asyik", "astrojim": "astagfirullahaladzim",
        "ath": "kalau begitu", "atuh": "kalau begitu", "ava": "avatar", "aws": "awas", "ayang": "sayang",
        "ayok": "ayo", "bacot": "banyak bicara", "bales": "balas", "bangdes": "pembangunan desa", "bangkotan": "tua",
        "banpres": "bantuan presiden", "bansarkas": "bantuan sarana kesehatan",
        "bazis": "badan amal, zakat, infak, dan sedekah", "bcoz": "karena", "beb": "sayang", "bejibun": "banyak",
        "belom": "belum", "bener": "benar", "ber2": "berdua", "berdikari": "berdiri di atas kaki sendiri",
        "bet": "banget", "beti": "beda tipis", "beut": "banget", "bgd": "banget", "bgs": "bagus",
        "bhubu": "tidur", "bimbuluh": "bimbingan dan penyuluhan", "bisi": "kalau-kalau", "bkn": "bukan", "bl": "beli",
        "blg": "bilang", "blm": "belum", "bls": "balas", "bnchi": "benci", "bngung": "bingung", "bnyk": "banyak",
        "bohay": "badan aduhai", "bokep": "porno", "bokin": "pacar", "bole": "boleh", "bolot": "bodoh",
        "bonyok": "ayah ibu", "bpk": "bapak", "brb": "segera kembali", "brngkt": "berangkat", "brp": "berapa",
        "brur": "saudara laki-laki", "bsa": "bisa", "bsk": "besok", "bu_bu": "tidur", "bubarin": "bubarkan",
        "buber": "buka bersama", "bujubune": "luar biasa", "buser": "buru sergap", "bwhn": "bawahan", "byar": "bayar",
        "byr": "bayar", "c8": "chat", "cabut": "pergi", "caem": "cakep", "cama-cama": "sama-sama",
        "cangcut": "celana dalam", "cape": "capek", "caur": "jelek", "cekak": "tidak ada uang", "cekidot": "coba lihat",
        "cemplungin": "cemplungkan", "ceper": "pendek", "ceu": "kakak perempuan", "cewe": "cewek", "cibuk": "sibuk",
        "cin": "cinta", "ciye": "cie", "ckck": "ck", "clbk": "cinta lama bersemi kembali", "cmpr": "campur",
        "cnenk": "senang", "congor": "mulut", "cow": "cowok", "coz": "karena", "cpa": "siapa", "gokil": "gila",
        "gombal": "suka merayu", "gpl": "tidak pakai lama", "gpp": "tidak apa-apa", "gretong": "gratis", "gt": "begitu",
        "gtw": "tidak tahu", "gue": "saya", "guys": "teman-teman", "gws": "cepat sembuh", "haghaghag": "tertawa",
        "hakhak": "tertawa", "handak": "bahan peledak", "hansip": "pertahanan sipil", "hellow": "halo", "helow": "halo",
        "hi": "hai", "hlng": "hilang", "hnya": "hanya", "houm": "rumah", "hrs": "harus",
        "hubad": "hubungan angkatan darat", "hubla": "perhubungan laut", "huft": "mengeluh",
        "humas": "hubungan masyarakat", "idk": "saya tidak tahu", "ilfeel": "tidak suka", "imba": "jago sekali",
        "imoet": "imut", "info": "informasi", "itung": "hitung", "isengin": "bercanda", "iyala": "iya lah",
        "iyo": "iya", "jablay": "jarang dibelai", "jadul": "jaman dulu", "jancuk": "anjing", "jd": "jadi",
        "jdikan": "jadikan", "jg": "juga", "jgn": "jangan", "jijay": "jijik", "jkt": "jakarta", "jnj": "janji",
        "jth": "jatuh", "jurdil": "jujur adil", "jwb": "jawab", "ka": "kakak", "kabag": "kepala bagian",
        "kacian": "kasihan", "kadit": "kepala direktorat", "kaga": "tidak", "kaka": "kakak",
        "kamtib": "keamanan dan ketertiban", "kamuh": "kamu", "kamyu": "kamu", "kapt": "kapten",
        "kasat": "kepala satuan", "kasubbid": "kepala subbidang", "kau": "kamu", "kbar": "kabar",
        "kcian": "kasihan", "keburu": "terlanjur", "kedubes": "kedutaan besar", "kek": "seperti", "keknya": "kayaknya",
        "keliatan": "kelihatan", "keneh": "masih", "kepikiran": "terpikirkan", "kepo": "mau tahu urusan orang",
        "kere": "tidak punya uang", "kesian": "kasihan", "ketauan": "ketahuan", "keukeuh": "keras kepala",
        "khan": "kan", "kibus": "kaki busuk", "kk": "kakak", "klian": "kalian", "klo": "kalau", "kluarga": "keluarga",
        "klwrga": "keluarga", "kmari": "kemari", "kmpus": "kampus", "kn": "kan", "knl": "kenal", "knpa": "kenapa",
        "kog": "kok", "kompi": "komputer", "komtiong": "komunis Tiongkok", "konjen": "konsulat jenderal", "koq": "kok",
        "kpd": "kepada", "kptsan": "keputusan", "krik": "garing", "krn": "karena", "ktauan": "ketahuan",
        "ktny": "katanya", "kudu": "harus", "kuq": "kok", "ky": "seperti", "kykny": "kayanya", "laka": "kecelakaan",
        "lambreta": "lambat", "lansia": "lanjut usia", "lapas": "lembaga pemasyarakatan", "lbur": "libur",
        "lekong": "laki-laki", "lg": "lagi", "lgkp": "lengkap", "lht": "lihat", "linmas": "perlindungan masyarakat",
        "lmyan": "lumayan", "lngkp": "lengkap", "loch": "loh", "lol": "tertawa", "lom": "belum", "loupz": "cinta",
        "lowh": "kamu", "lu": "kamu", "luchu": "lucu", "luff": "cinta", "luph": "cinta", "lw": "kamu", "lwt": "lewat",
        "maaciw": "terima kasih", "mabes": "markas besar", "macem-macem": "macam-macam", "madesu": "masa depan suram",
        "maen": "main", "mahatma": "maju sehat bersama", "mak": "ibu", "makasih": "terima kasih", "malah": "bahkan", 
        "malu2in": "memalukan", "mamz": "makan", "manies": "manis", "mantep": "mantap", "markus": "makelar kasus", 
        "mba": "mbak", "mending": "lebih baik", "mgkn": "mungkin", "mhn": "mohon", "miker": "minuman keras",
        "milis": "mailing list", "mksd": "maksud", "mls": "malas", "mnt": "minta", "moge": "motor gede", 
        "mokat": "mati", "mosok": "masa", "msh": "masih", "mskpn": "meskipun", "msng2": "masing-masing",
        "muahal": "mahal", "muker": "musyawarah kerja", "mumet": "pusing", "muna": "munafik", 
        "munaslub": "musyawarah nasional luar biasa", "musda": "musyawarah daerah", "muup": "maaf", "muuv": "maaf",
        "nal": "kenal", "nangis": "menangis", "naon": "apa", "napol": "narapidana politik", "naq": "anak", 
        "narsis": "bangga pada diri sendiri", "nax": "anak", "ndak": "tidak", "ndut": "gendut",
        "nekolim": "neokolonialisme", "nelfon": "menelepon", "ngabis2in": "menghabiskan", "ngakak": "tertawa",
        "ngambek": "marah", "ngampus": "pergi ke kampus", "ngantri": "mengantri", "ngapain": "sedang apa", 
        "ngaruh": "berpengaruh", "ngawur": "berbicara sembarangan", "ngeceng": "kumpul bareng-bareng", 
        "ngeh": "sadar", "ngekos": "tinggal di kos", "ngelamar": "melamar", "ngeliat": "melihat",
        "ngemeng": "bicara terus-terusan", "ngerti": "mengerti", "nggak": "tidak", "ngikut": "ikut",
        "nginep": "menginap", "ngisi": "mengisi", "ngmg": "bicara", "ngocol": "lucu", "ngomongin": "membicarakan", 
        "ngumpul": "berkumpul", "ni": "ini", "nyasar": "tersesat", "nyariin": "mencari", "nyiapin": "mempersiapkan",
        "nyiram": "menyiram", "nyok": "ayo", "o/": "oleh", "ok": "ok", "priksa": "periksa", "pro": "profesional",
        "psn": "pesan", "psti": "pasti", "puanas": "panas", "qmo": "kamu", "qt": "kita", "rame": "ramai",
        "raskin": "rakyat miskin", "red": "redaksi", "reg": "register", "rejeki": "rezeki", "renstra": "rencana strategis",
        "reskrim": "reserse kriminal", "sni": "sini", "somse": "sombong sekali", "sorry": "maaf", "sosbud": "sosial-budaya",
        "sospol": "sosial-politik", "sowry": "maaf", "spd": "sepeda", "sprti": "seperti", "spy": "supaya",
        "stelah": "setelah", "subbag": "subbagian", "sumbangin": "sumbangkan", "sy": "saya", "syp": "siapa",
        "tabanas": "tabungan pembangunan nasional", "tar": "nanti", "taun": "tahun", "tawh": "tahu", "tdi": "tadi",
        "te2p": "tetap", "tekor": "rugi", "telkom": "telekomunikasi", "telp": "telepon", "temen2": "teman-teman",
        "tengok": "menjenguk", "terbitin": "terbitkan", "tgl": "tanggal", "thanks": "terima kasih",
        "thd": "terhadap", "thx": "terima kasih", "tipi": "TV", "tkg": "tukang", "tll": "terlalu", "tlpn": "telepon",
        "tman": "teman", "tmbh": "tambah", "tmn2": "teman-teman", "tmph": "tumpah", "tnda": "tanda", "tnh": "tanah",
        "togel": "toto gelap", "tp": "tapi", "tq": "terima kasih", "trgntg": "tergantung", "trims": "terima kasih",
        "cb": "coba", "y": "ya", "munfik": "munafik", "reklamuk": "reklamasi", "sma": "sama", "tren": "trend",
        "ngehe": "kesal", "mz": "mas", "analisise": "analisis", "sadaar": "sadar", "sept": "september",
        "nmenarik": "menarik", "zonk": "bodoh", "rights": "benar", "simiskin": "miskin", "ngumpet": "sembunyi", 
        "hardcore": "keras", "akhirx": "akhirnya", "solve": "solusi", "watuk": "batuk", "ngebully": "intimidasi",
        "masy": "masyarakat", "still": "masih", "tauk": "tahu", "mbual": "bual", "tioghoa": "tionghoa", 
        "ngentotin": "senggama", "kentot": "senggama", "faktakta": "fakta", "sohib": "teman", "rubahnn": "rubah",
        "trlalu": "terlalu", "nyela": "cela", "heters": "pembenci", "nyembah": "sembah", "most": "paling", 
        "ikon": "lambang", "light": "terang", "pndukung": "pendukung", "setting": "atur", "seting": "akting", 
        "next": "lanjut", "waspadalah": "waspada", "gantengsaya": "ganteng", "parte": "partai", "nyerang": "serang",
        "nipu": "tipu", "ktipu": "tipu", "jentelmen": "berani", "buangbuang": "buang", "tsangka": "tersangka", 
        "kurng": "kurang", "ista": "nista", "less": "kurang", "koar": "teriak", "paranoid": "takut",
        "problem": "masalah", "tahi": "kotoran", "tirani": "tiran", "tilep": "tilap", "happy": "bahagia",
        "tak": "tidak", "penertiban": "tertib", "uasai": "kuasa", "mnolak": "tolak", "trending": "trend", 
        "taik": "tahi", "wkwkkw": "tertawa", "ahokncc": "ahok", "istaa": "nista", "benarjujur": "jujur",
        "mgkin": "mungkin"}

processed_comments = []

for sentence in data['customer_isi_komen']:
    # Remove all the special characters
    processed_comment = re.sub(r'\W', ' ', str(sentence))
    
    # Converting to Lowercase
    processed_comment = processed_comment.lower()
    
    #Remove number 
    processed_comment = re.sub(r'\d+', ' ', processed_comment)

    # remove all single characters
    processed_comment = re.sub(r'\s+[a-zA-Z]\s+', ' ', processed_comment)
    
    #remove duplicate character
    pattern=re.compile(r"(.)\1{1,}",re.DOTALL)
    processed_comment=pattern.sub(r"\1",processed_comment)

    #Corrected Slang words
    words = processed_comment.split()
    rfrm=[slangs[word] if word in slangs else word for word in words]
    processed_comment= " ".join(rfrm)

    #remove stopword
    factory = StopWordRemoverFactory()
    f = open("stopwords-tala.txt", "r")
    more_stopword = [] #menambahkan stopword
    for line in f:
        stripped_line = line.strip()
        line_list = stripped_line.split()
        more_stopword.append(line_list[0])
    f.close()
    stopwords = factory.get_stop_words() + more_stopword
    temp = [t for t in re.findall(r'\b[a-z]+-?[a-z]+\b',processed_comment) if t not in stopwords]
    processed_comment = ' '.join(temp)

    #stemming
    stemmer = StemmerFactory().create_stemmer()
    processed_comment = stemmer.stem(processed_comment)

    #Subtitusing multiple spaces with single space
    processed_comment = re.sub(r'\s+', ' ', processed_comment, flags=re.I)

    processed_comments.append(processed_comment)

In [5]:
processed_comments

['salah baik fasilitas sedia pilih kamar kamar tempat luas bersih suka jalan pagi keliling sdh lelah area pandang roftopnya bagus sarapanya variasi cari lokasi makan terima kasih layan bagus',
 'mobil delica java heritage keluarga endah hernawan hajar hernawan audrey vialita hernanda aldy hernanda fabian hernanda rudi driver terima kasih rudi pecat sopir fabian fod and travel asia',
 'layak pilih kunjung kota lokasi strategis kamar nyaman kolam renang aman dalam jadi layak pilih',
 'juara lokasi keliling makan juara lot parkir luas interior instagramable nuansa jawa kamar deluxe luas banding kelas pilih makan lengkap lezat staf ramah responsif atas keluh',
 'megah bangun fasilitas tunjang kadangkala diri java heritage suguh lengkap megah lengkap fasilitas gedung kerapihan kolam renang view pandang lepas alam balkon lantai restonya pandang indah gunung selamet nan agung nun belah utara sejuk udara khas menu makan tradisional unik menu modern lezat jadi suasana sarap tambah semangat',
 '

<h1>
Vektorisasi
</h1>

In [6]:
from sklearn.feature_extraction.text import CountVectorizer
tf_vectorizer = CountVectorizer(max_df=1.0, min_df=1)
tf = tf_vectorizer.fit_transform(processed_comments)
#hasil representasi
tf_terms = tf_vectorizer.get_feature_names()
print(tf_vectorizer.get_feature_names())
matrix = tf.toarray()
print(matrix)

['ac', 'acara', 'ada', 'adat', 'ade', 'adem', 'aditional', 'aga', 'agam', 'agent', 'agoda', 'agung', 'ah', 'ahahaha', 'air', 'ajak', 'ajar', 'aju', 'akan', 'akses', 'aksi', 'akurat', 'al', 'alam', 'alamat', 'alat', 'aldy', 'alek', 'alias', 'alih', 'alternatif', 'alu', 'alun', 'aman', 'ambar', 'ambil', 'amenities', 'amerika', 'amplas', 'an', 'anak', 'and', 'aneh', 'aneka', 'angin', 'angka', 'angkat', 'anjak', 'antar', 'anti', 'antik', 'apa', 'apek', 'api', 'apik', 'arah', 'area', 'areal', 'arik', 'aroma', 'artis', 'asa', 'asal', 'asam', 'asia', 'asik', 'asin', 'aspek', 'aston', 'at', 'atas', 'atur', 'audrey', 'aula', 'avanza', 'awan', 'awat', 'ayam', 'background', 'badan', 'bagua', 'bagus', 'bahan', 'baik', 'balcony', 'balkon', 'balon', 'balrom', 'bandara', 'banding', 'bandung', 'banget', 'bangun', 'bangunanya', 'bantal', 'bantu', 'banyumas', 'bar', 'barang', 'batang', 'batas', 'bath', 'bathfoam', 'bathtub', 'batu', 'baturaden', 'bau', 'bawa', 'bawah', 'bayar', 'be', 'bebas', 'bed', 'be

<h1>
Menggunakan 5 Topik Teratas
</h1>

In [7]:
# panggil class LDA
from sklearn.decomposition import LatentDirichletAllocation as LDA
n_topics = 5 #untuk mendapatkan jumlah topik terbaik perlu trial
lda = LDA(n_components=n_topics, learning_method='batch', random_state=0).fit(tf)
lda

LatentDirichletAllocation(n_components=5, random_state=0)

In [8]:
#training LDA
vsm_topics = lda.transform(tf)
#tampilkan hasil
print(vsm_topics.shape)
vsm_topics

(119, 5)


array([[0.0068426 , 0.97287546, 0.00673103, 0.0067749 , 0.00677601],
       [0.00694955, 0.00693355, 0.00691056, 0.97228508, 0.00692126],
       [0.01273175, 0.01272259, 0.01265829, 0.94925665, 0.01263072],
       [0.00753287, 0.96989336, 0.00749834, 0.0074984 , 0.00757702],
       [0.00412958, 0.98350508, 0.004117  , 0.00412136, 0.00412697],
       [0.00331792, 0.00331809, 0.98672548, 0.00332555, 0.00331297],
       [0.00341551, 0.00343872, 0.00337813, 0.00338609, 0.98638155],
       [0.98576786, 0.00356885, 0.00354764, 0.00356062, 0.00355504],
       [0.01067223, 0.95729716, 0.01058828, 0.01079593, 0.0106464 ],
       [0.00731057, 0.0072451 , 0.00728716, 0.00726948, 0.97088768],
       [0.00614305, 0.97548814, 0.00608971, 0.00613432, 0.00614477],
       [0.00554387, 0.00550459, 0.00547327, 0.00553811, 0.97794016],
       [0.00425899, 0.00430235, 0.00424639, 0.98296963, 0.00422265],
       [0.00814929, 0.96748462, 0.00806166, 0.00814917, 0.00815525],
       [0.96289269, 0.00940847, 0.

In [9]:
#Tampilkan nilai-nilai setiap fitur
print(lda.components_)


[[1.19973002 0.20000145 0.20000352 ... 0.20000062 0.20000059 0.20000047]
 [3.19346328 4.19951679 2.19967556 ... 0.20000049 0.20000045 0.20000036]
 [0.20646458 0.20000278 0.20000683 ... 0.20000119 0.20000107 0.2000009 ]
 [2.20033899 0.20000204 1.19979728 ... 0.20000082 0.20000082 0.20000066]
 [0.20000312 0.20047695 0.20051681 ... 1.19999689 1.19999707 1.19999761]]


In [10]:
#hasil label topic model untuk setiap dokumen
import numpy as np
topics = np.argmax(vsm_topics, axis=1)
topics

array([1, 3, 3, 1, 1, 2, 4, 0, 1, 4, 1, 4, 3, 1, 0, 1, 3, 0, 3, 3, 2, 0,
       0, 4, 3, 0, 1, 4, 1, 4, 3, 1, 1, 0, 3, 1, 1, 2, 3, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 3, 1, 4, 1, 3, 2, 1, 1, 1, 1, 0, 0, 1,
       3, 3, 4, 1, 2, 0, 0, 1, 3, 1, 0, 4, 3, 4, 1, 0, 2, 3, 0, 1, 4, 1,
       3, 0, 2, 2, 1, 0, 1, 4, 4, 4, 4, 0, 3, 2, 1, 0, 4, 2, 1, 3, 4, 1,
       1, 0, 4, 4, 2, 1, 1, 3, 0], dtype=int64)

In [11]:
#mencetak word fitur dengan nilai tertinggi pada setiap topik
n_top_words = 4 # jumlah fitur tertinggi yang kita tentukan
topic_words = {}
for topic, comp in enumerate(lda.components_):
 word_idx = np.argsort(comp)[::-1][:n_top_words]
 # store the words most relevant to the topic
 topic_words[topic] = [tf_vectorizer.get_feature_names()[i]+' '+str(comp[i]) for i in word_idx]

In [12]:
for topic, words in topic_words.items():
 print('Topic: %d' % topic)
 print(' %s' % ', '.join(words))

Topic: 0
 kamar 44.95037351018805, inap 24.3022291144703, luas 22.48355057424015, bersih 15.23926144799837
Topic: 1
 kamar 74.02180356596469, luas 41.376250696779515, kolam 26.53741444660403, renang 25.23551574225794
Topic: 2
 kamar 12.779895885116645, kota 8.517582174429503, nyaman 7.496012733438991, renang 6.93207648352401
Topic: 3
 kamar 28.20166167295463, renang 15.20331222682952, kolam 14.203328948262397, kota 12.2064099217546
Topic: 4
 kamar 26.046265365774786, makan 13.835483418169021, renang 13.460268458267048, inap 12.539357819740447


<h1>
Menggunakan 10 Topik Teratas
</h1>

In [13]:
# panggil class LDA
from sklearn.decomposition import LatentDirichletAllocation as LDA
n_topics = 10 #untuk mendapatkan jumlah topik terbaik perlu trial
lda = LDA(n_components=n_topics, learning_method='batch', random_state=0).fit(tf)
lda

LatentDirichletAllocation(random_state=0)

In [14]:
#training LDA
vsm_topics = lda.transform(tf)
#tampilkan hasil
print(vsm_topics.shape)
vsm_topics

(119, 10)


array([[0.00333435, 0.62140227, 0.00333382, ..., 0.00333408, 0.35192639,
        0.00333393],
       [0.00344856, 0.00344865, 0.00344833, ..., 0.00344863, 0.96896273,
        0.00344917],
       [0.00625093, 0.00625127, 0.00625151, ..., 0.00625097, 0.00625082,
        0.00625106],
       ...,
       [0.00232592, 0.00232594, 0.00232584, ..., 0.002326  , 0.00232586,
        0.00232602],
       [0.00555638, 0.00555666, 0.00555624, ..., 0.94999427, 0.00555615,
        0.00555622],
       [0.97999823, 0.00222251, 0.00222239, ..., 0.00222242, 0.00222245,
        0.00222238]])

In [15]:
#Tampilkan nilai-nilai setiap fitur
print(lda.components_)


[[1.1000014  0.1        0.1        ... 0.1        0.1        0.1       ]
 [1.09999787 1.09999584 1.09999923 ... 0.1        0.1        0.1       ]
 [0.1        0.1        0.1        ... 0.1        0.1        0.1       ]
 ...
 [1.09999835 0.1        0.1        ... 0.1        0.1        1.1       ]
 [1.10000218 0.1        0.1        ... 0.1        0.1        0.1       ]
 [1.09999891 0.1        0.1        ... 0.1        1.1        0.1       ]]


In [16]:
#hasil label topic model untuk setiap dokumen
import numpy as np
topics = np.argmax(vsm_topics, axis=1)
topics

array([1, 8, 3, 1, 5, 5, 9, 7, 1, 9, 1, 4, 8, 1, 7, 1, 6, 9, 2, 5, 2, 0,
       7, 9, 7, 9, 1, 6, 1, 4, 5, 1, 5, 5, 4, 7, 1, 7, 9, 1, 9, 0, 1, 0,
       1, 7, 0, 6, 9, 8, 5, 7, 9, 7, 1, 4, 1, 3, 7, 6, 2, 9, 7, 0, 8, 7,
       7, 3, 4, 1, 8, 6, 0, 1, 3, 9, 8, 7, 3, 4, 1, 5, 2, 9, 7, 8, 4, 5,
       8, 0, 2, 3, 1, 8, 0, 6, 4, 4, 4, 7, 4, 2, 1, 0, 4, 5, 1, 5, 4, 7,
       7, 7, 4, 0, 7, 1, 6, 7, 0], dtype=int64)

In [17]:
#mencetak word fitur dengan nilai tertinggi pada setiap topik
n_top_words = 4 # jumlah fitur tertinggi yang kita tentukan
topic_words = {}
for topic, comp in enumerate(lda.components_):
 word_idx = np.argsort(comp)[::-1][:n_top_words]
 # store the words most relevant to the topic
 topic_words[topic] = [tf_vectorizer.get_feature_names()[i]+' '+str(comp[i]) for i in word_idx]

In [18]:
for topic, words in topic_words.items():
 print('Topic: %d' % topic)
 print(' %s' % ', '.join(words))

Topic: 0
 kamar 18.870051966874158, inap 15.264265272749322, pilih 8.903652999334229, sarap 7.6194038396320645
Topic: 1
 kamar 43.503063798994596, luas 19.80482972091912, bagus 18.677131551143503, makan 16.331279611050906
Topic: 2
 renang 6.0555753767601095, kamar 5.099943820253244, kolam 5.042418857135264, nyaman 4.100035888895036
Topic: 3
 kamar 9.995040009769426, renovasi 4.100041130896445, bersih 4.099988600275811, kolam 4.084015171057234
Topic: 4
 kamar 13.132958391667241, makan 11.6745751348799, renang 11.670878162576814, kolam 9.638494903579396
Topic: 5
 kamar 14.099991030069608, nyaman 10.100050836282408, kota 9.10006903865884, gunung 7.078459306767805
Topic: 6
 kamar 8.191300262476082, layan 6.100067339597893, bersih 5.100049392851896, ramah 4.100039833155047
Topic: 7
 kamar 30.468491662529395, luas 17.812403878173903, kolam 12.09997659338341, renang 12.099968505872127
Topic: 8
 kamar 18.853741083217606, luas 7.682815097030212, bersih 6.79808943147419, bangun 6.752728708655957